<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>PsTiger.Tests.TestLibrary</RootNamespace>
    <AssemblyName>PsTiger.Tests.TestLibrary</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Execution\Execution.csproj" />
  </ItemGroup>

</Project>
