#!/usr/bin/env bash
#
# Использует ildasm для дизассемблирования исполняемых файлов .NET в текстовое представление MSIL.

set -o errexit

print_usage() {
    echo "Usage: $0 <program.c>"
    echo "Uses ildasm to decompile .NET program into MSIL"
}

if [ $# -ne 1 ]; then
    echo "Error: missing arguments" 1>&2
    print_usage
    exit 1
fi

if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    print_usage
    exit 0
fi

INPUT_FILE="$1"
OUTPUT_FILE="${INPUT_FILE%.*}.il"

ildasm "$INPUT_FILE" -utf8 "-out=$OUTPUT_FILE"
echo "Disassembled OK, see $OUTPUT_FILE"