<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>PsTiger.Tests.Interpreter.Specs</RootNamespace>
    <AssemblyName>PsTiger.Tests.Interpreter.Specs</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="Reqnroll.xUnit" Version="3.3.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2">
    <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Grammar\Grammar.csproj" />
    <ProjectReference Include="..\..\src\Interpreter\Interpreter.csproj" />
    <ProjectReference Include="..\TestLibrary\TestLibrary.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ReqnrollFeatureFile Update="Features\Records.feature">
      <NormalizedLogicalName>Features/Arrays.feature</NormalizedLogicalName>
      <NormalizedRelativeDir>Features/</NormalizedRelativeDir>
      <CodeBehindFile>Features/Arrays.feature.cs</CodeBehindFile>
      <MessagesFile>obj\Debug/net10.0/Features/Arrays.feature.ndjson</MessagesFile>
      <MessagesResourceName>Features/Arrays.feature.ndjson</MessagesResourceName>
      <FeatureFileResourceName>Features/Arrays.feature</FeatureFileResourceName>
    </ReqnrollFeatureFile>
  </ItemGroup>

</Project>
