<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>PsTiger.MsilCodegen</RootNamespace>
    <AssemblyName>PsTiger.MsilCodegen</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ast\Ast.csproj" />
  </ItemGroup>

</Project>
